### ISSUE TITLE
getweatherstatusのレスポンスに"#"が含まれていた場合にエラーが発生します

### ISSUE THREAD

**Issue by Dotinkasra** [eggplants/zutool#117]
### 環境
Python 3.13.0
zutool==0.1.1

### 概要
コマンドラインからweather_statusを取得しようとした場合に以下のエラーが発生する場合があります。

```
$ zutool ws 13113
ValidationError: 2 validation errors for ErrorResponse
error_code
  Field required [type=missing, input_value={'place_name': '東京都...'pressure_level': '3'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
error_message
  Field required [type=missing, input_value={'place_name': '東京都...'pressure_level': '3'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
```

また、Pythonからインポートしてget_weather_statusを実行すると同様のエラーが発生する場合があります。

<details><summary>Traceback</summary>

```
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/xbar/plugins/zutool.1h.py", line 19, in get_zutool
    zp = zutool.get_weather_status(code)
  File "/Users/user/.asdf/installs/python/3.13.0/lib/python3.13/site-packages/zutool/api.py", line 63, in get_weather_status
    return __get("/getweatherstatus", city_code, GetWeatherStatusResponse)
  File "/Users/user/.asdf/installs/python/3.13.0/lib/python3.13/site-packages/zutool/api.py", line 49, in __get
    err_res = ErrorResponse.model_validate_json(res.text)
  File "/Users/user/.asdf/installs/python/3.13.0/lib/python3.13/site-packages/pydantic/main.py", line 625, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 2 validation errors for ErrorResponse
error_code
  Field required [type=missing, input_value={'place_name': '東京都...'pressure_level': '3'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
error_message
  Field required [type=missing, input_value={'place_name': '東京都...'pressure_level': '3'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
```
</details>

### 原因
API（getweatherstatus）のレスポンス内のtempの値に「"#"」が含まれる場合にエラーが発生します。
<img width="1104" alt="スクリーンショット 2024-11-12 16 12 00" src="https://github.com/user-attachments/assets/1af01da1-f2cd-4b13-996e-8e69ba4e859a">

### 対策
[_WeatherStatusByTimeクラスのtemp変数](https://github.com/eggplants/zutool/blob/8fc5cccdf433e139b1d12990d73c994589cc03bb/zutool/models/get_weather_status.py#L15)で文字列を許容してバリデーションを追加することが考えられますが、APIのレスポンスに「"#"」が含まれる（頭痛ーるのアプリ上では該当時間の気温が空欄の状態となる）条件がよくわからず、発生頻度もあまり高くはありませんので、対応されるかはお任せいたします。

**Comment by eggplants** [comment]
ありがとうございます。報告の通り温度のデータが欠損値 (`#`)になる場合を想定していなかったので今回のエラーが発生しているようです。

---

また、次回発生したタイミングでお手数ですが[Wayback Machine](https://web.archive.org/save)などで `https://zutool.jp/api/getweatherstatus/:city_code` のアーカイブをとっていただけるとありがたいです。

**Comment by eggplants** [comment]
https://pypi.org/project/zutool/0.2.0/
